version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - uname -a
      - pip install -r requirements.txt
      - pwd
      - ls -ltr
      - ls -ltr  tests/
      - pip install -e src/
      - python -m pytest tests/ -v
      # run mypy as part of the build:
      - python -m mypy src/
      # run and check black as part of the build, throws up if formatting is off:
      - python -m black --check .
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
  post_build:
    commands:
      - echo "we are in the post build phase"
