version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - uname -a
#      - yum update -y
#      - yum upgrade -y
#      - yum install -y python3-venv
#      - python3.9 -m venv test_venv
#      - . test_venv/bin/activate
#      - pip install --upgrade pip
#      - pip install .
#cd /opt/prelude && python -m black --check .
#echo "### - Running isort checks ###"
#cd /opt/prelude && python -m isort . -c
#echo "### - Running mypy checks ###"
#cd /opt/prelude && python -m mypy .
      - pip install -r requirements.txt
      - pwd
      - ls -ltr
      - ls -ltr  tests/
      - python -m pytest tests/ -v
      - python -m mypy app_name/
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
  post_build:
    commands:
      - echo "we are in the post build phase"
